# Generated by Django 4.2.13 on 2024-05-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0002_reservation_delete_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Booking',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='num_people',
            new_name='no_of_people',
        ),
    ]
