# Generated by Django 4.2.13 on 2024-05-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0003_rename_reservation_booking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_people',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='contact',
            new_name='phone',
        ),
    ]
