# Generated by Django 4.2.13 on 2024-05-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0006_alter_payment_customer_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
