# Generated by Django 4.2.13 on 2024-05-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0010_rename_card_name_cardpayment_name1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cardPayment',
        ),
    ]
