# Generated by Django 4.2.13 on 2024-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0014_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('booking_datetime', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('total_people', models.IntegerField()),
                ('payment_per_person', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
