# Generated by Django 4.2.13 on 2024-05-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0015_paymentinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinvoice',
            old_name='customer_name',
            new_name='name',
        ),
    ]
