# Generated by Django 4.2.13 on 2024-05-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0017_delete_paymentinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(max_length=5)),
                ('payment_status', models.CharField(default='success', max_length=20)),
            ],
        ),
    ]
