# Generated by Django 4.2.13 on 2024-05-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0018_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='cardPayment',
        ),
    ]
