# Generated by Django 4.2.13 on 2024-05-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0019_rename_payment_cardpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardpayment',
            old_name='card_number',
            new_name='cardnumber',
        ),
        migrations.RenameField(
            model_name='cardpayment',
            old_name='expiration_date',
            new_name='expirationdate',
        ),
    ]
