# Generated by Django 4.2.13 on 2024-05-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0020_rename_card_number_cardpayment_cardnumber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cardPayment',
        ),
    ]
