# Generated by Django 4.2.13 on 2024-07-07 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EasyDineApp', '0025_profile_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Login',
        ),
    ]
