# Generated by Django 4.2.13 on 2024-09-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDineApp', '0027_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
