# Generated by Django 4.2.13 on 2024-05-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='restaurant_images')),
            ],
        ),
    ]
