# Generated by Django 4.2.13 on 2024-07-07 18:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_owner', '0003_rest_owner_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rest_owner_Login',
            new_name='Login_owner',
        ),
    ]
